# Generated by Django 6.0.1 on 2026-04-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_review_reviewer_alter_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
