# Generated by Django 6.0.1 on 2026-02-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('cuisine_type', models.CharField(choices=[('american', 'American'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('japanese', 'Japanese'), ('mediterranean', 'Mediterranean'), ('other', 'Other')], default='other', max_length=50)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('available', models.BooleanField(default=True)),
                ('prep_time', models.IntegerField(help_text='Preparation time in minutes')),
                ('servings', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
