# Generated by Django 6.0.1 on 2026-04-08 21:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cuisine_type',
            field=models.CharField(choices=[('american', 'American'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('japanese', 'Japanese'), ('mediterranean', 'Mediterranean'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='prep_time',
            field=models.PositiveIntegerField(help_text='Preparation time in minutes'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='servings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='listings.listing')),
            ],
        ),
    ]
