# Generated by Django 6.0.1 on 2026-04-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_latitude_listing_longitude_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='customization_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of main ingredients'),
        ),
        migrations.AddField(
            model_name='listing',
            name='spice_level',
            field=models.CharField(blank=True, choices=[('none', 'Not Spicy'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('extra_hot', 'Extra Hot')], max_length=20),
        ),
    ]
