# Generated by Django 6.0.1 on 2026-04-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookprofile',
            name='accepted_payments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='available_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='certified_details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='cuisine_specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='food_safety_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='payment_notes',
            field=models.CharField(blank=True, help_text='e.g. Venmo: @username', max_length=200),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text='How/where to pick up orders'),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='signature_dishes',
            field=models.TextField(blank=True, help_text='What are you known for?'),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cookprofile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cookprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell customers about yourself'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
